
server:
  port: 8081 #Tomcat??
spring:
  dubbo:
    application:
      name: springboot-dubbo-demo #???
    registry:
      address: zookeeper://124.221.168.242 #zookeeper??
      port: 2181 #???????
      registry-type: com.example.springbootdubbpbiz.registry.MyZookeeperRegistryFactory
    protocol:
      name: dubbo
      port: 20891 #dubbo???????
    scan: com.example.springbootdubbpbiz.remoteapi.impl #?????


    provider:
      filter: dubboLogFilter

dubbo:
  env: dev2