server:
    port: 8080
    servlet:
        context-path: /my


#
spring:
    profiles:
        active: dev
    datasource:
        username: root
        password: 19941029lz09
        url: jdbc:mysql://124.221.168.242:3306/test
        driver-class-name: com.mysql.jdbc.Driver

#    redis:
#        host: 124.221.168.242
#        port: 6379
#        password: linzhou
    redis:
        redisson:
            # 配置单点模式
            config: classpath:redisson.yml
        jedis:
            pool:
                max-active: 8  #最大连接数
                max-wait: 3 #最大阻塞等待时间(负数表示没限制)
                max-idle: 8 #最大空闲




mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.example


logging:
    config: classpath:log/log4j2.xml
    level:
        cn.jay.repository: trace





#Apollo 配置
#app:
#    id: myProjectDubbo
#apollo:
##    cacheDir: /opt/data/                       #配置本地配置缓存目录
##    cluster: default                           #指定使用哪个集群的配置
#    meta: http://apollo.linzhou.link
##    autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
#    bootstrap:
#        enabled: true
#        eagerLoad:
#            enabled: false