server:
    port: 8080

spring:
    datasource:
        username: root
        password: 19941029lz09
        url: jdbc:mysql://127.0.0.1:3306/test
        driver-class-name: com.mysql.jdbc.Driver


mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.example