server:
    port: 8080
    servlet:
        context-path: /my



spring:
    datasource:
        username: root
        password: 19941029lz09
        url: jdbc:mysql://124.221.168.242:3306/test
        driver-class-name: com.mysql.jdbc.Driver

    redis:
        url: redis//124.221.168.242:6379


mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.example